export const studentsData = [
  {
    id: 1,
    name: "Aman Sharma",
    image: "https://i.pravatar.cc/150?img=12",
    email: "aman@gmail.com",
    courses: 2,
    progress: 75,
    lastActive: "Inactive",
  },
  {
    id: 2,
    name: "Neha Verma",
    image: "https://i.pravatar.cc/150?img=32",
    email: "neha@gmail.com",
    courses: 3,
    progress: 40,
    lastActive: "Active",
  },
  {
    id: 3,
    name: "Rohit Kumar",
    image: "https://i.pravatar.cc/150?img=45",
    email: "rohit@gmail.com",
    courses: 1,
    progress: 90,
    lastActive: "Inactive",
  },
  {
    id: 4,
    name: "Pooja Singh",
    image: "https://i.pravatar.cc/150?img=25",
    email: "pooja@gmail.com",
    courses: 4,
    progress: 55,
    lastActive: "Active",
  },
  {
    id: 5,
    name: "Rahul Mehta",
    image: "https://i.pravatar.cc/150?img=18",
    email: "rahul@gmail.com",
    courses: 2,
    progress: 30,
    lastActive: "Inactive",
  },
  {
    id: 6,
    name: "Anjali Gupta",
    image: "https://i.pravatar.cc/150?img=41",
    email: "anjali@gmail.com",
    courses: 5,
    progress: 80,
    lastActive: "Active",
  },
  {
    id: 7,
    name: "Vikas Yadav",
    image: "https://i.pravatar.cc/150?img=52",
    email: "vikas@gmail.com",
    courses: 1,
    progress: 65,
    lastActive: "Inactive",
  },
];
